aiVersion: apps/v1
kind: Deployment
metadata:
   name: mydeployments
spec:
   replicas: 2
   selector:     
    matchLabels:
     name: nginx
   template:
     metadata:
       name: testpod
       labels:
         name: deployment
     spec:
        containers:
          - name: node
            image: aadi557/node:latest
        imagePullSecrets:
          - name: docsec




